### PR TITLE
Edits to mirror code and scheduling

### PR DESCRIPTION
**Pull request by e-linear**
I updated the mirror.py code to connect to Supabase and update the 'Agencies' and 'Data Sources' tables. I also edited the workflow to do this every day at 8AM (this time can be changed, of course). 

Some notes:

- I created two duplicate tables in Supabase labeled 'Agencies' and 'Data Sources' (vs. what was already there: 'agencies' and 'data_sources' to match the AGENCIES_TABLE_NAME and SOURCES_TABLE_NAME in the mirror.py file. (And to test the code without overwriting the other tables, just in case).
- I used upsert to insert/update the tables. 
- Supabase/JSON had trouble with the "datetime" objects, so I had to code a workaround that converted these to strings but left the 'None' values untouched.
- Running the update can be a bit slow - will post an update with estimated times.

### CODE REVIEW

**Comment by e-linear** [comment]
> I updated the mirror.py code to connect to Supabase and update the 'Agencies' and 'Data Sources' tables. I also edited the workflow to do this every day at 8AM (this time can be changed, of course).
> 
> Some notes:
> 
>     * I created two duplicate tables in Supabase labeled 'Agencies' and 'Data Sources' (vs. what was already there: 'agencies' and 'data_sources' to match the AGENCIES_TABLE_NAME and SOURCES_TABLE_NAME in the mirror.py file. (And to test the code without overwriting the other tables, just in case).
> 
>     * I used upsert to insert/update the tables.
> 
>     * Supabase/JSON had trouble with the "datetime" objects, so I had to code a workaround that converted these to strings but left the 'None' values untouched.
> 
>     * Running the update can be a bit slow - will post an update with estimated times.

Updates:

- I've run it a couple times to make sure that it's working as it should. I had to make the primary key for the Agencies table be the uid, and the primary key in the Data Sources table be 'name' in order for it to properly update and not create new records.
- Timing: It takes a little over half an hour to do the full Agencies table update (~23k records) and under 5 mins to do the Data Sources table update (~1.5k records). We should discuss whether updating like this is the right approach or if we want to just re-upload a full CSV (which I haven't tested the timing of).

**Comment by e-linear** [comment]
#12

**Comment by e-linear** [comment]
One thing to note is this doesn't address API key usage - however, it seems this is just a PAT (personal access token) swap, and I wanted to confirm the original code (using API keys) worked before making that switch.

**Comment by mbodeantor** [comment]
Nice! Still testing the code but it looks good overall. The one thing I saw was the "agency_described" field in Data Sources is coming in as a list. If that could be parsed to just a string, we could use that column as a foreign key link to Agencies for API queries.

**Comment by mbodeantor** [comment]
One other minor thing, looks like the supabase package needs to be added to the Pipfile.

**Comment by e-linear** [comment]
Oh great catch, will update!
________________________________

**Comment by mbodeantor** [comment]
The runtimes should be fine for now, especially for a daily schedule. I bet the full CSV upload would be slower, but might be worth a test. We could also compare the state of Airtable to the state of the Supabase table and then only upsert rows we know changed, but it should be fine for now.

**Comment by mbodeantor** [comment]
I haven't been able to get the mirror script to complete still with my current internet access, but I'm good to close this out after the agency_described change.

**Comment by e-linear** [comment]
@mbodeantor Just uploaded the updated code which mirrors the entire tables (this time including the Counties table, just to be safe). It preserves the old functionality to write to CSV/JSON but does not automatically do this unless specified.

**Comment by mbodeantor** [comment]
@e-linear Got this error when I tried to run mirror.py:
```
'message': 'new row violates row-level security policy for table "counties"'
```

**Comment by mbodeantor** [comment]
Oh nm just needs the service role instead of the public key

**Comment by e-linear** [comment]
> Oh nm just needs the service role instead of the public key

Oh yeah, sorry! I've been using service role key for these updates so we don't need to have any row policies.

**Comment by mbodeantor** [comment]
@e-linear I'm little concerned the script still times out for me locally. Have you seen it complete with github actions?

**Comment by e-linear** [comment]
@mbodeantor No, I've been running it locally. It does take a while (the Agencies table especially), but it successfully completes for me locally & is updating the tables. I'll run some tests right now with github actions

**Comment by e-linear** [comment]
@mbodeantor Getting this error when trying to run the github actions script: "Actions in this workflow must be: within a repository owned by Police-Data-Accessibility-Project." Seems like it might be an access issue?: https://github.com/orgs/community/discussions/25488

**Comment by mbodeantor** [comment]
@josh-chamberlain I don't see a policy set up that would prevent this. Maybe we need one?

**Comment by josh-chamberlain** [comment]
@mbodeantor @e-linear I recently broke this while trying to accomplish something else. I'll be able to fix it this afternoon

**Comment by mbodeantor** [comment]
The one other thing on here, the script is starting to get fairly long and the flow has changed a bit. I think it makes sense the way you have it set up to only create the csv and json, but could you rearrange the functions so it reads a little more top to bottom?

**Comment by e-linear** [comment]
@mbodeantor Good point. It has two sets of functions with similar naming schemes, but I separated them to keep things clean & preserve the original functionality. I just organized it so all of the CSV/JSON functions are first (though unused) and all of the Supabase functions are second, followed by the main call. If you think the Supabase ones should go first, I can swap those, too.

**Comment by e-linear** [comment]
> @mbodeantor Good point. It has two sets of functions with similar naming schemes, but I separated them to keep things clean & preserve the original functionality. I just organized it so all of the CSV/JSON functions are first (though unused) and all of the Supabase functions are second, followed by the main call. If you think the Supabase ones should go first, I can swap those, too.

Alternatively, I can put the functions in top-to-bottom order so instead of it bein

**Comment by mbodeantor** [comment]
Yeah I think it makes more sense to have the supabase functions first, so the full_mirror_to_supabase function definition would be first, followed by get_full_table_data, then get_full_fieldnames etc. Also process_county and process_county_uid only need to defined once (outside the for loop).

**Comment by e-linear** [comment]
@mbodeantor I reread your message and see you meant re-organize all of the functions, will do that now! I had them in the original order but you're right they should be moved around.

**Comment by e-linear** [comment]
_Now_ it should be in the order you specified, @mbodeantor. Sorry for the original misread!

**Review by mbodeantor — COMMENTED** [review]
Awesome! Actually process_county and process_county_uid don't even need to be inside process_agencies_full, they could go after prep_counties. Other than that and process_data_link_full before process_data_full, it looks good to go!

**Comment by mbodeantor** [comment]
Thanks for all those changes! Looking good

**Review by mbodeantor — APPROVED** [review]

**Pull request merged**
